def handle_exception():
    print('handle exception')